databaseChangeLog:
  - changeSet:
      id: Create order table
      author: Elshan Akbarov
      changes:
        - createTable:
            tableName: orders
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: account_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: restaurant_id
                  type: bigint
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: int
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValue: now()
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: TIMESTAMP
                  defaultValue: now()
                  constraints:
                    nullable: false
