#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SPRING
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:4306}/route_order?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SPRING CLOUD
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cloud:
    config:
      enabled: false
    stream:
      kafka:
        binder:
          auto-create-topics: false
          brokers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
      bindings:
        orderCreatedOutput:
          destination: orderCreated.test.topic


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ADAPTERS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

commandhandler:
  enabled: true
adapters:
  payment:
    enabled: true
    retryAttempts: 3
    retryDelay: 1
    baseUrl: http://${PAYMENT_API_HOST:localhost}:8090
    paymentPath: /api/v1/payments







#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# INFRA
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

server:
  port: 8091
kafka:
  enabled: true

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# LOGGING
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logging:
  level:
    com.hexagonaldemo.paymentapi: INFO
